<div class="container">
  <ul>
    <li class="dropdown">
    <a href="#" data-toggle="dropdown">
    <h1 class="menu-title">
    <img src="image/icons/info28.png" width="34" height="31" alt=""/> Additional Information</h1>

     <i class="icon-arrow">
    </i>
    </a>
      <ul class="dropdown-menu">
        <table>
          <tbody>
            <tr>
              <td width="75" height="66"></td>
              <td width="364">Visa Information</td>
              </tr>
            <tr>
              <td height="70"></td>
              <td><p>Face Sheet</p>
                <p></p></td>
              </tr>
            <tr>
              <td height="70"></td>
              <td><p>Accom/City info</p></td>
              </tr>
            </tbody>
</table>
      </ul>