<div class="container">
  <ul>
    <li class="dropdown">
    <a href="#" data-toggle="dropdown">
    <h1 class="menu-title">
    <img src="image/icons/user158.png" width="34" height="31" alt=""/>  Student Experience </h1>
    <i class="icon-arrow">
    </i>
    </a>
      <ul class="dropdown-menu">
        <table width="1000" height="144" >
          <tbody>
            <tr>
              <td width="56" height="66"></td>
              <td width="122">Link etc</td>
              <td width="135"></td>
              </tr>
            <tr>
              <td height="70"></td>
              <td></td>
              <td></td>
              </tr>
            </tbody>
</table>
      </ul>
</ul>